### ISSUE TITLE
Kapitel 2.1 Lemma 8 Beweis (aktuell Seite 10)

### ISSUE THREAD

**Issue by hollesse** [karlstroetmann/Analysis#12]
Hallo Herr Stroetmann,
kann es sein, dass in dem oben genannten Beweis nicht auf Lemma 7, sondern auf Lemma 6 verwiesen werden sollte, oder habe ich gerade einen Denkfehler?

Liebe Grüße
Joshua Töpfer

**Comment by karlstroetmann** [comment]
Hallo Herr Töpfer,

ja, da haben Sie recht, ich habe den Fehler korrigiert.

Viele Grüße,
Karl Stroetmann


> Joshua Töpfer <notifications@github.com> hat am 13. April 2016 um 21:43
> geschrieben:
> 
> 
>  Hallo Herr Stroetmann,
>  kann es sein, dass in dem oben genannten Beweis nicht auf Lemma 7, sondern
> auf Lemma 6 verwiesen werden sollte, oder habe ich gerade einen Denkfehler?
> 
>  Liebe Grüße
>  Joshua Töpfer
> 
>  —
>  You are receiving this because you are subscribed to this thread.
>  Reply to this email directly or view it on GitHub
> <https://github.com/karlstroetmann/Analysis/issues/12>
> 
> 
> 



________________________________________________________________________

*Prof. Dr. Karl Stroetmann*

Professor für Lehraufgaben in der Angewandten Informatik

*Duale Hochschule Baden-Württemberg Mannheim*
*Angewandte Informatik*
Coblitzallee 1-9
68163 Mannheim

Tel.: +49 (0)621 4105 - 1376
Fax: +49 (0)621 4105 - 1194
Email: karl.stroetmann@dhbw-mannheim.de
Skype: karlstroetmann
