### ISSUE TITLE
Seite 146 Satz ergibt keinen Sinn

### ISSUE THREAD

**Issue by hollesse** [karlstroetmann/Analysis#19]
Hallo Herr Stroetmann,
aus Seite 146 unter Punkt 7.2.1 der Satz _"Wir mit der Ketten-Regel."_ ergibt irgendwie keinen Sinn. 

Mit besten Grüßen
Joshua Töpfer

**Comment by karlstroetmann** [comment]
Hallo Herr Töpfer,
 
da fehlte das Wort "beginnen". Ich habe es korrigiert.  Vielen Dank für den
Hinweis.
 
Viele Grüße,
Karl Stroetmann
 

> Joshua Töpfer <notifications@github.com> hat am 28. Juni 2016 um 13:08
> geschrieben:
> 
> 
>  Hallo Herr Stroetmann,
>  aus Seite 146 unter Punkt 7.2.1 der Satz "Wir mit der Ketten-Regel." ergibt
> irgendwie keinen Sinn.
> 
>  Mit besten Grüßen
>  Joshua Töpfer
> 
>  —
>  You are receiving this because you are subscribed to this thread.
>  Reply to this email directly, view it on GitHub
> https://github.com/karlstroetmann/Analysis/issues/19 , or mute the thread
> https://github.com/notifications/unsubscribe/ADIy0u0LgY1M07NL0t1OdsvQiIa3Qjytks5qQQCygaJpZM4I__Oz
> .
> 
>   
> 

 

________________________________________________________________________

*Prof. Dr. Karl Stroetmann*

Professor für Lehraufgaben in der Angewandten Informatik

*Duale Hochschule Baden-Württemberg Mannheim*
*Angewandte Informatik*
Coblitzallee 1-9
68163 Mannheim

Tel.: +49 (0)621 4105 - 1376
Fax: +49 (0)621 4105 - 1194
Email: karl.stroetmann@dhbw-mannheim.de
Skype: karlstroetmann
